name: Fake ANSYS to Codebeamer

on:
  workflow_dispatch:

jobs:

  simulation:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate Fake ANSYS Result
        run: python fake_ansys.py

      - name: Publish to Codebeamer
        env:
          CODEBEAMER_USER: ${{ secrets.CODEBEAMER_USER }}
          CODEBEAMER_PASSWORD: ${{ secrets.CODEBEAMER_PASSWORD }}
        run: python integration/publish_to_codebeamer.py
