name: Virtual Simulation

on:
  workflow_dispatch:

jobs:
  simulation:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - run: python fake_ansys.py

    - run: python evaluate.py

    - run: python publish_to_codebeamer.py
